### ISSUE TITLE
Update MX bypass and excess flow monthly distributions

### ISSUE THREAD

**Issue by rabutler-usbr** [usbr/DIT_CRSS_DB#4]
https://github.com/BoulderCodeHub/crss.v5/issues/24

**Comment by khumphreysBOR** [comment]
Updated monthly distributions in the DIT for YUMA OPERATIONS:Welton Mohawk Bypass Flows and DELIVERY TO MEXICO IN EXCESS OF TREATY REQUIREMENTS:OVER DELIVERY TO MEXICO. 

Updated monthly distributions to annual average monthly distributions from CRMMS (MexicanTreatyDelivery:MexicoBypass.Diversion Requested
and MexicanTreatyDelivery:MexicoExcess.Diversion Requested)

![Issue_4_MX_Bypass_Excess_Monthly_Distributions](https://user-images.githubusercontent.com/115026889/203119330-eb774ffd-33f2-4571-a404-5b95272d72b5.PNG)

[Update MX bypass and excess flow monthly distributions.xlsx](https://github.com/usbr/DIT_CRSS_DB/files/10059019/Update.MX.bypass.and.excess.flow.monthly.distributions.xlsx)

**Comment by khumphreysBOR** [comment]
Added to DIT in[ 2.9.5](https://github.com/usbr/DIT_CRSS_DB/commit/2e225be405eafd305ab34d68687714c684c0274c)

Updated in https://github.com/BoulderCodeHub/crss.v5/pull/103
